image: andrzejtracz/php-node

variables:
  MYSQL_DATABASE: casper_test
  MYSQL_ROOT_PASSWORD: casper_test

services:
  - mysql:5.7

cache:
  paths:
    - node_modules/
    - vendor/

stages:
  - test

test:
  stage: test
  script:
    - php -v
    - deployer --version
    - node -v
    - npm -v
    - composer install
    - npm install
    - npm run prod
    - composer seed:test
    - composer test
