image: andrzejtracz/php-node

variables:
  MYSQL_DATABASE: casper_test

services:
  - mysql:5.7

cache:
  paths:
    - node_modules/
    - vendor/

before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

stages:
  - test

test:
  stage: test
  script:
    - php -v
    - deployer --version
    - node -v
    - npm -v
    - composer install
    - composer seed:test
    - composer test
